app/routes.php
Route::post('validate', 'AuthController@codigo');

Route::get('protection', 'ProtectionController@generateProtection');
Route::get('refresh-protection', 'ProtectionController@generateProtection');

// Validamos los datos de inicio de sesión.
Route::post('login', 'AuthController@postLogin');


Route::group(array('before' => 'auth'), function () {
    
    Route::get('usuarios/changePass/{id}',['as' => 'usuarios.changePass',"uses"=>"usuariosController@cambiarClave"]);


    Route::get("usuarios/clave", array('as' => 'usuarios.clave', 'uses' => 'UsuariosController@getCambiarClave'));

    Route::post("usuarios/clave", array('as' => 'usuarios.clave', 'uses' => 'UsuariosController@postCambiarClave'));
    
    Route::get("estadisticas/requerimientos", array('as' => 'estadistica.requerimientos', 'uses' => 'EstadisticasController@requerimientos'));
    Route::get("estadisticas/getRequerimientos/mes", array('as' => 'estadistica.getRequerimientos', 'uses' => 'EstadisticasController@getReqMes'));
    Route::get("estadisticas/getRequerimientosPorTipo", array('as' => 'estadistica.getRequerimientosTipo', 'uses' => 'EstadisticasController@getReqTipo'));
    Route::get("estadisticas/getTiposReq", array('as' => 'estadistica.getTiposOficios', 'uses' => 'EstadisticasController@getTiposOficios'));
    Route::get("estadisticas/getOrganismos", array('as' => 'estadistica.getOrganismos', 'uses' => 'EstadisticasController@getOrganismos'));
    Route::get("estadisticas/getReqPorOrganismos", array('as' => 'estadistica.getReqPorOrganismos', 'uses' => 'EstadisticasController@getReqPorOrganismos'));


});


Route::post("pedidos_captura/agregarDocumento", array("as" => 'pedidos_captura.agregarDocumento', 'uses' => 'PedidosCapturaController@agregarDocumento'));



Route::when('archivos/*','auth');

Route::group(array('before'=>'cambio_clave'),function() {
    Route::group(array('before' => 'auth'), function () {

            Route::post("usuarios/aceptar",array("as" => "usuarios.aceptar", "uses" => "UsuariosController@aceptar"));
        Route::get('protection', 'ProtectionController@generateProtection');
        Route::get('refresh-protection', 'ProtectionController@generateProtection'); 
        
        Route::resource('oficios','OficiosController');
        Route::get('oficios/busqueda',array('as'=>'oficios.buscar','uses'=>'OficiosController@index'));
        Route::get('files/descargar',array('as'=>'archivos.descargar','uses'=>function(){
            $path = Input::get('q');
            return Response::download($path);
        }));


        //Permisos para el usuario superadmin (5), solo el puede editar y para el accesso a la administracion del sistema
            Route::group(array('before' => 'role:1-5,inicio','after'=>'oficiosModificacion'), function () {
            Route::get("admin/oficios_anio",["as"=>"oficios_anio.index","uses"=>"OficiosController@adminOficiosByAnio"]);
            Route::resource("admin", "AdminController");
            Route::get('consultas_positivas',["as"=>"consultas_positivas.index","uses"=>"ConsultaPositivaController@index"]);
            Route::get('consultas_positivas/{idConsulta}',["as"=>"consulta_positiva.show","uses"=>"ConsultaPositivaController@show"]);

            Route::get("oficios_anio",["as"=>"oficios_anio.get","uses"=>"OficiosController@getOficiosByAnio"]);


            Route::post("miembros/validarDatos",array('as' => 'miembros.validarDatos','uses'  => 'MiembrosController@validarDatos'));
            Route::post("miembros/{id}/actualizar",array('as' => 'miembros.actualizar','uses'  => 'MiembrosController@actualizar'));
            Route::post("miembros/eliminarOperador",array('as' => 'miembros.eliminarOperador','uses'  => 'MiembrosController@eliminarOperador'));
            Route::post("miembros/agregarOperador",array('as' => 'miembros.agregarOperador','uses'  => 'MiembrosController@agregarOperador'));
            Route::post("miembros/listadoOperadores",array('as' => 'miembros.listadoOperadores','uses'  => 'MiembrosController@listadoOperadores'));
            Route::post("miembros/listadoResponsables",array('as' => 'miembros.listadoResponsables','uses'  => 'MiembrosController@listadoResponsables'));
            Route::post("miembros/eliminarResponsable",array('as' => 'miembros.eliminarResponsable','uses'  => 'MiembrosController@eliminarResponsable'));
            Route::post("miembros/agregarResponsable",array('as' => 'miembros.agregarResponsable','uses'  => 'MiembrosController@agregarResponsable'));

            Route::get("suborganismos/organismo/{idOrganismo}",array('as' => 'suborganismo.byorganismo','uses'  => 'SubOrganismoController@getSubOrganismoByIdOrg'));

            Route::resource("miembros", "MiembrosController",array('except' => array('show','index')));


            Route::resource("usuarios", "UsuariosController");
            Route::resource("panel","AdminController");
            Route::resource("mails","CorreosController");
            Route::resource("subOrganismos","SubOrganismoController");
            Route::post('usuarios/restablecer/clave',array("as"=>"usuarios.restablecer","uses"=>"UsuariosController@RestablecerClave"));
//            Route::resource("solicitud_paradero", "OficioSolicitudParaderoController",array('except' => array('show','create','update','edit')));
            Route::resource("solicitud_paradero", "PersonaExtraviadaController",array('except' => array('show','create','update','edit')));
            Route::post("solicitud_paradero/agregarCelular",array('as' => 'solicitud_paradero.agregarCelular','uses'  => 'PersonaExtraviadaController@agregarCelular'));
            Route::post("solicitud_paradero/eliminarCelular",array('as' => 'solicitud_paradero.eliminarCelular','uses'  => 'PersonaExtraviadaController@eliminarCelular'));
//            Route::post("solicitud_paradero/agregarCelular",array('as' => 'solicitud_paradero.agregarCelular','uses'  => 'OficioSolicitudParaderoController@agregarCelular'));
//            Route::post("solicitud_paradero/eliminarCelular",array('as' => 'solicitud_paradero.eliminarCelular','uses'  => 'OficioSolicitudParaderoController@eliminarCelular'));
            Route::get("solicitud_paradero/{rute}/{name}/mostrar_archivo",['as' => 'solicitud_paradero.mostrar_archivo','uses' => 'PersonaExtraviadaController@show']);
            Route::get('solicitud_paradero/show/{id}',["as"=>'solicitud_paradero.show',"uses"=>"PersonaExtraviadaController@showReporte"]);
            Route::resource("secuestro_elementos", "SecuestroElementosController",array('except' => array('show','create','update','edit')));
            Route::resource("secuestro_armas", "SecuestroArmasController",array('except' => array('show','create','update','edit')));
            Route::resource("secuestro_vehicular", "PedidosSecuestroVehicularController",array('except' => array('show','create','update','edit')));
            Route::resource("prohibicion_salida", "ProhibicionSalidaPaisController",array('except' => array('show','create','update','edit')));
            Route::resource("pedidos_captura", "PedidosCapturaController",array('except' => array('show','create','update','edit')));
            Route::resource("medidas_restrictivas", "MedidasRestrictivasController",array('except' => array('show','create','update','edit')));
            Route::resource("solicitud_paradero2", "SolicitudParaderoReqJudController",array('except' => array('show','create','update','edit')));
            Route::resource("habeas_corpus", "HabeasCorpusController",array('except' => array('show','create','update','edit')));
            Route::resource("otras_medidas", "OtrasMedidasController",array('except' => array('show','create','update','edit')));
            Route::get("oficios/vencimiento/{id}",["as"=>"oficios.confirmar.vencimiento","uses"=>"OficiosController@confirmarVencimiento"]);
            Route::get('oficios/autoridad/{idOficio}',["as"=>"oficios.autoridad","uses"=>"OficiosController@getAutoridad"]);
            Route::post('oficios/autoridad/{idOficio}',["as"=>"oficios.autoridad","uses"=>"OficiosController@setAutoridad"]);
            Route::get('grupos_correos',["as"=>"grupo_correos.index","uses"=>"GruposCorreosController@index"]);
            Route::get('grupos_correos/getGrupos',["as"=>"grupo_correos.getGrupos","uses"=>"GruposCorreosController@getGrupos"]);
            Route::post('grupos_correos/grupos/create',["as"=>"grupo_correos.create","uses"=>"GruposCorreosController@createGrupo"]);
            Route::post('grupos_correos/grupos/miembros/add',["as"=>"grupo_correos.miembros.add","uses"=>"GruposCorreosController@createMiembroOrganismo"]);
            Route::post('grupos_correos/grupos/miembros/remove',["as"=>"grupo_correos.miembros.remove","uses"=>"GruposCorreosController@removeMiembroOrganismo"]);
            Route::get('grupos_correos/get/organismos',["as"=>"grupo_correos.getOrganismos","uses"=>"GruposCorreosController@getOrganismos"]);
            Route::get('/grupos_correos/gruposMiembros/{idGrupo}',["as"=>"grupo_correos.gruposMiembros","uses"=>"GruposCorreosController@getMiembrosByGrupo"]);

            Route::get('consultas_positivas',["as"=>"consultas_positivas.index","uses"=>"ConsultaPositivaController@index"]);
            Route::get('consultas_positivas/{idConsulta}',["as"=>"consulta_positiva.show","uses"=>"ConsultaPositivaController@show"]);



        });

        //Permisos para el usuario supervisor y de carga, permisos para create (formulario de carga) y store (guardar el formulario en la bbdd)

        Route::get('/', 'OficiosController@inicio');
        Route::get('inicio',array("as"=>"inicio","uses"=>'OficiosController@inicio'));


        Route::group(array('before'=>'role:1-3-5,inicio|oficioVisto|oficiosModificacion'),function(){
            Route::get('solicitud_paradero/{id}/edit',["as"=>'solicitud_paradero.edit',"uses"=>"PersonaExtraviadaController@edit"]);

app/controllers/MiembrosController.php
<?php

use Administracion\Helpers\HelperOperadores;
use Administracion\Helpers\HelperResponsable;
use Administracion\Manager\ManagerMiembro;
use Administracion\Repositories\RepoMiembro;
use Administracion\Repositories\RepoMiembroxOperador;
use Administracion\Repositories\RepoMiembroxResponsable;
use Combos\Entities\CombosOrganismos;

/**
 * Created by PhpStorm.
 * User: damian
 * Date: 10/08/15
 * Time: 16:00
 */
class MiembrosController extends \BaseController
{

    private $repoMiembro;
    protected $ruta;
    protected $view;
    private $helperOperadores;
    private $helperResponsable;
    private $repoMiembroxOperador;
    private $repoMiembroxResponsable;

    function __construct(RepoMiembro $repoMiembro,
                         HelperOperadores $helperOperadores,
                         HelperResponsable $helperResponsable,
                         RepoMiembroxOperador $repoMiembroxOperador,
                         RepoMiembroxResponsable $repoMiembroxResponsable
                        )
    {
        $this->repoMiembro = $repoMiembro;
        $this->ruta    = "miembros.";
        $this->view    = "miembros/";
        $this->helperOperadores = $helperOperadores;
        $this->helperResponsable = $helperResponsable;
        $this->repoMiembroxOperador = $repoMiembroxOperador;
        $this->repoMiembroxResponsable = $repoMiembroxResponsable;
    }

    public function index()
    {
        $miembros = $this->repoMiembro->all();
        return View::make($this->view."listado",compact('miembros'));
    }

    public function create()
    {
        $operadores = array();
        $responsables = array();
        Session::put('operadores',$operadores);
        Session::put('responsables',$responsables);


        $model = $this->repoMiembro->getModel();
//        dd($model);
        $form_data = array('id'=>'form','route' => $this->ruta.'store', 'method' => 'POST', 'action' => 'return false');
        $action = "Agregar";
        $combosOrganismos = CombosOrganismos::remember(60)->lists('descripcion','id');
        $responsables = "";
        $operadores = "";
        return View::make($this->view.'form',compact("model","form_data","action","combosOrganismos","responsables","operadores"));
    }

    public function agregarOperador()
    {
        return $this->helperOperadores->agregarOperador();
    }

    public function eliminarOperador()
    {
        return $this->helperOperadores->eliminarOperador();
    }

    public function agregarResponsable()
    {
        return $this->helperResponsable->agregarResponsable();
    }

    public function eliminarResponsable()
    {
        return $this->helperResponsable->eliminarResponsable();
    }

    public function validarDatos()
    {
        $data      = Input::all();
        $model     = null;
        $valid     = true;
        $idMiembro = Input::get('id',false);
        
        $model = $this->repoMiembro->firstOrNew(["id"=>$idMiembro]);
        
        $manager = new ManagerMiembro($model,$data);
        
        $validacion  = $manager->isValid();
        
        if($validacion["valid"])
        {
            if(count(\Session::get("responsables")) == 0){
               $validacion["valid"] = false;
               $validacion["mensaje"] = "Debe ingresar al menos un responsable";  
            } 

            if(count(\Session::get("operadores")) == 0){
                $validacion["valid"] = false;
                $validacion["mensaje"] = "Debe ingresar al menos un operador";;  
            } 
        }

        return $validacion;

    }

    public function store(){
        $model   = $this->repoMiembro->nuevoMiembro();
        $data    = Input::all();
        $manager = new ManagerMiembro($model,$data);
        $manager->save();

        $lista_responsables = \Session::get("responsables");
        foreach($lista_responsables as $responsable)
            $this->repoMiembroxResponsable->agregarResponsable($manager->getEntity()->id,$responsable);

        $lista_operadores = \Session::get("operadores");
        foreach($lista_operadores as $operador)
            $this->repoMiembroxOperador->agregarOperador($manager->getEntity()->id,$operador);

        return Redirect::route($this->ruta."index");
//        dd($_POST);
    }

    public function edit($id)
    {
        $lista_responsables = $this->repoMiembroxResponsable->darResponsablesXMiembro($id);

        $lista_operadores = $this->repoMiembroxOperador->darOperadoresXMiembro($id);

//        $espacios = array();
        Session::put('responsables',$lista_responsables);
        Session::put('operadores',$lista_operadores);
        $responsables = $this->helperResponsable->listadoResponsables($lista_responsables);

        $operadores = "";
        $cancelar = route($this->ruta.'index') ;

        $combosOrganismos = CombosOrganismos::remember(60)->lists('descripcion','id');
        $model = $this->repoMiembro->find($id);
        $action = "Editar";
        $form_data = ['id'=>'form','route' =>[$this->ruta.'actualizar',$id], 'method' => 'POST', 'action' => 'return false'];
        return View::make($this->view."form",compact("model","action","form_data","combosOrganismos","responsables","operadores","cancelar"))
            ->with("ruta",$this->ruta);

    }

    public function listadoResponsables()
    {
        $lista = Session::get("responsables");
        return $this->helperResponsable->listadoResponsables($lista);
    }

    public function listadoOperadores()
    {
        $lista = Session::get("operadores");
        return $this->helperOperadores->listadoOperadores($lista);
    }

    public function actualizar($id)
    {
        $model = $this->repoMiembro->find($id);
        $data    = Input::all();
        $manager = new ManagerMiembro($model,$data);
        $manager->save();

//        dd($manager);
        $this->repoMiembroxResponsable->eliminarResponsableXMiembro($id);
        $lista_responsables = \Session::get("responsables");
        foreach($lista_responsables as $responsable)
            $this->repoMiembroxResponsable->agregarResponsable($manager->getEntity()->id,$responsable);

        $this->repoMiembroxOperador->eliminarOperadorXMiembro($id);
        $lista_operadores = \Session::get("operadores");
        foreach($lista_operadores as $operador)
            $this->repoMiembroxOperador->agregarOperador($manager->getEntity()->id,$operador);

        return Redirect::route($this->ruta."index");
    }


    public function show($id){
        $model = $this->repoMiembro->find($id);
        return View::make('miembros.show')->with('miembro',$model);
    }

}

app/views/miembros/form.blade.php
@extends ('header')
<style>
    input{
        text-transform: none !important;
    }
</style>

@section('scripts')
<script>
    $().ready(function () {

        @if($model->id)
            var destino = "{{ Route('miembros.listadoResponsables') }}";
            $.ajax({
                type: "Post",
                url: destino,
                async: false,
                success: function(respuesta){
                    $("#div_responsables").html(respuesta);
                }
            });

            var destino = "{{ Route('miembros.listadoOperadores') }}";
            $.ajax({
                type: "Post",
                url: destino,
                async: false,
                success: function(respuesta){
                    $("#div_operadores").html(respuesta);
                }
            });

            $("form").keypress(function(e) {
                if (e.which == 13) {
                    return false;
                }
            });
        @endif

        function validarEmail(email) {
            var expr = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            if ( !expr.test(email) )
                return false;
            else
                return true;
        }

        $("#btnAgregarOperador").click(function(){
            if($("#nombre_operador").val())
            {
                var datos = "nombre_operador="+$("#nombre_operador").val();
                var destino = "{{ Route('miembros.agregarOperador') }}";
                $.ajax({
                    type: "Post",
                    url: destino,
                    data: datos,
                    async: false,
                    success: function(respuesta){
                        $("#nombre_operador").val("");
                        $("#div_operadores").html(respuesta);
                        $("#nombre_operador").focus();
                    }
                });

            }

        });

        $("#btnAgregarResponsable").click(function(){
            if($("#nombre_responsable").val() == "")
            {
                $("#contenido-modal").html("Debe ingresar un nombre de responsable");
                $("#confirmacion").modal(function(){show:true});
            }
            else if(!validarEmail($("#email_responsable").val()))
            {
                $("#contenido-modal").html("Debe ingresar un email de responsable correcto");
                $("#confirmacion").modal(function(){show:true});
            }
            else if($("#nombre_responsable").val())
            {
                var datos = "nombre_responsable="+$("#nombre_responsable").val()+"&email_responsable="+$("#email_responsable").val()+"&telefono_responsable="+$("#telefono_responsable").val();
                var destino = "{{ Route('miembros.agregarResponsable') }}";
                $.ajax({
                    type: "Post",
                    url: destino,
                    data: datos,
                    async: false,
                    success: function(respuesta){

                        $("#nombre_responsable").val("");
                        $("#email_responsable").val("");
                        $("#telefono_responsable").val("");
                        $("#div_responsables").html(respuesta);
                        $("#nombre_responsable").focus();
                    }
                });

            }


        });

        $("#btnAceptar").click(function(){
            var datos = $('#form').serialize();
            var destino = "{{ Route('miembros.validarDatos') }}";
            $.ajax({
                type: "Post",
                url: destino,
                data: datos,
                async: true,
                success: function(respuesta){
                    if(!respuesta.valid)
                    {
                        console.log(respuesta.mensajes);
                        $("#contenido-modal").html(respuesta.mensaje);
                        return $("#confirmacion").modal(function(){show:true});
                    }
                    
                    $('#form').submit();
                    
                }

            })

        });
    });


</script>
@endsection

@section ('title') {{$action}} Miembro @stop

@section ('content')
    <h1>{{$action}} Miembro</h1>
    <div class="alert alert-danger fade in" style="display:none" id="errores">


    </div>

    {{ Form::model($model,$form_data, array('role' => 'form')) }}
    {{ Form::hidden('id',null,['id' => 'id']) }}
    <div class="row">
        <div class="form-group col-md-4">
            {{ Form::label('id_organismo','Organismo') }}
            {{ Form::select('id_organismo',$combosOrganismos,null,array('class'=>'form-control'))}}
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            {{ Form::label('nombre_area', 'Nombre de la Oficina/Area') }}
            {{ Form::text('nombre_area', null, array('placeholder' => 'Ingrese el nombre de la oficina/area', 'class' => 'form-control')) }}
        </div>
        <div class="form-group col-md-6">
            {{ Form::label('direccion_area', 'Dirección de la Oficina/Area') }}
            {{ Form::text('direccion_area', null, array('placeholder' => 'Ingrese la direccion de la oficina/area', 'class' => 'form-control')) }}
        </div>
        <div class="form-group col-md-6">
            {{ Form::label('telefono_area', 'Teléfono de la Oficina/Area') }}
            {{ Form::text('telefono_area', null, array('placeholder' => 'Ingrese el teléfono de la oficina/area', 'class' => 'form-control')) }}
        </div>
        <div class="form-group col-md-6">
            {{ Form::label('email_area', 'Email de la Oficina/Area') }}
            {{ Form::text('email_area', null, array('placeholder' => 'Ingrese el email de la oficina/area', 'class' => 'form-control')) }}
        </div>
    </div>

    <br>


    <div class="panel panel-info">
        <div class="panel-heading">Datos del responsable</div>
        <div class="panel-body">
            <div class="form-inline">
                <div class="form-group">
                    {{ Form::label('nombre_responsable', 'Nombre del responsable',['class'=>'sr-only']) }}
                    {{ Form::text('nombre_responsable', null, array('placeholder' => 'Nombre del responsable', 'class' => 'form-control')) }}
                </div>
                <div class="form-group">
                    {{ Form::label('email_responsable', 'Email del responsable',['class'=>'sr-only']) }}
                    {{ Form::text('email_responsable', null, array('placeholder' => 'Email del responsable', 'class' => 'form-control')) }}
                </div>
                <div class="form-group">
                    {{ Form::label('telefono_responsable', 'Telefono del responsable',['class'=>'sr-only']) }}
                    {{ Form::text('telefono_responsable', null, array('placeholder' => 'Telefono del responsable', 'class' => 'form-control')) }}
                </div>
                {{ Form::button('Agregar responsable', array('type' => 'button', 'class' => 'btn btn-success','id'=>'btnAgregarResponsable')) }}

            </div>
        </div>
    </div>
    <div id="div_responsables"></div>
    <br>
    <div class="panel panel-info">
        <div class="panel-heading">Datos del operador</div>
        <div class="panel-body">
            <div class="form-inline">
                <div class="form-group">
                    {{ Form::label('nombre_operador', 'Nombre del operador',['class'=>'sr-only']) }}
                    {{ Form::text('nombre_operador', null, array('placeholder' => 'Nombre del operador', 'class' => 'form-control')) }}
                </div>

                {{ Form::button('Agregar operador', array('type' => 'button', 'class' => 'btn btn-success','id'=>'btnAgregarOperador')) }}

            </div>
        </div>
    </div>
    <div id="div_operadores"></div>
    <div class="row">

        <div class="form-group col-md-4">

            {{ Form::button('Guardar', array('type' => 'button', 'class' => 'btn btn-primary','id'=>'btnAceptar')) }}
        </div>
    </div>
    @include("components.modal")
    {{ Form::close() }}
@stop

app/views/miembros/listado.blade.php
@extends ('header')
@section ('title') Listado de miembros @stop
@section ('content')
    @if(Auth::user()->id_perfil == 1 or Auth::user()->id_perfil == 5)
    <a href="{{ route('miembros.create') }}"><button class="btn btn-primary" >Cargar Miembro <i class="glyphicon glyphicon-user"></i></button></a>
    @endif

    <h2>Listados de miembros</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Organismo</th>
            <th>Area</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Email</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        @foreach($miembros as $key => $value)
            <tr>
                <td>{{ $value->getOrganismo->descripcion }}</td>
                <td>{{ $value->nombre_area }}</td>
                <td>{{ $value->direccion_area }}</td>
                <td>{{ $value->telefono_area }}</td>
                <td>{{ $value->email_area }}</td>
                <td>
                    @if(Auth::user()->id_perfil == 1 or Auth::user()->id_perfil == 5)
                    <a href="{{ route('miembros.edit', $value->id) }}" class="btn btn-success btn-sm">
                        Editar
                    </a>
                    @endif
                    <a href="{{ route('miembros.show', $value->id) }}" class="btn btn-success btn-sm">
                        Ver
                    </a>
                </td>

            </tr>
        @endforeach
        </tbody>
    </table>
@stop


@section('jquery')


@stop

app/views/miembros/listadoOperadores.blade.php
<script>
    $().ready(function(){

        $(".btnEliminar").click(function(){
            var datos = "id_operador="+this.id;
            var destino = "{{ Route('miembros.eliminarOperador') }}";
            $.ajax({
                type: "Post",
                url: destino,
                data: datos,
                async: false,
                success: function(respuesta){
                    $("#div_operadores").html(respuesta);
                }

            })
        });
    });
</script>

<div class="panel panel-info" id="listado_archivos" data-bool="existe">
    <div class="panel-heading">Listado de operadores</div>
    <div class="panel-body">
        <div class="row">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>
                        Operador
                    </th>
                    <th>
                        Eliminar
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($lista as $value)
                    <tr>
                        <td>{{ $value['nombre_operador'] }} </td>
                        <td><input type="button" value="Eliminar" id="{{ $value['id_operador'] }}" class="btn btn-default btn-sm btnEliminar" /></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/miembros/listadoResponsables.blade.php
<div class="panel panel-info" id="listado_archivos" data-bool="existe">
    <div class="panel-heading">Listado de responsables</div>
    <div class="panel-body">
        <div class="row">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Telefono</th>
                    <th>Eliminar</th>
                </tr>
                </thead>
                <tbody>
                @foreach($lista as $value)
                    <tr >
                        <td style="text-transform: none">{{ $value['nombre_responsable'] }} </td>
                        <td style="text-transform: none">{{ $value['email_responsable'] }} </td>
                        <td >{{ $value['telefono_responsable'] }} </td>
                        <td><input type="button" value="Eliminar" id="{{ $value['id_responsable'] }}" class="btn btn-default btn-sm btnEliminarResponsable" /></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $().ready(function(){

        $(".btnEliminarResponsable").click(function(){
            var datos = "id_responsable="+this.id;
            var destino = "{{ Route('miembros.eliminarResponsable') }}";
            $.ajax({
                type: "Post",
                url: destino,
                data: datos,
                async: false,
                success: function(respuesta){
                    $("#div_responsables").html(respuesta);
                }

            })
        });
    });
</script>