app/routes.php
<?php

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Oficios\Entities\Oficios;




if(\Config::get('config.dmz')) {
    Route::get('oficios/indexJson','OficiosController@indexJson');
    Route::get('oficios/listanegravehiculos','OficiosController@getSecuestrosVehicular');
}





Route::get('test',function(){
    $oficios = new Oficios();
    $oficios = $oficios->where('created_at','<=',Carbon::now()->subYears(1))->get();
    dd($oficios->toArray());



});


Route::group(array('before' => 'auth'), function () {

    Route::get('ip',function(){
    });
});




Route::get('login', 'AuthController@showLogin');
Route::get('validate', 'AuthController@codigo');
Route::post('validate', 'AuthController@codigo');

Route::get('protection', 'ProtectionController@generateProtection');
Route::get('refresh-protection', 'ProtectionController@generateProtection');

// Validamos los datos de inicio de sesión.
Route::post('login', 'AuthController@postLogin');


Route::group(array('before' => 'auth'), function () {
    
    Route::get('usuarios/changePass/{id}',['as' => 'usuarios.changePass',"uses"=>"usuariosController@cambiarClave"]);


    Route::get("usuarios/clave", array('as' => 'usuarios.clave', 'uses' => 'UsuariosController@getCambiarClave'));

    Route::post("usuarios/clave", array('as' => 'usuarios.clave', 'uses' => 'UsuariosController@postCambiarClave'));
    
    Route::get("estadisticas/requerimientos", array('as' => 'estadistica.requerimientos', 'uses' => 'EstadisticasController@requerimientos'));
    Route::get("estadisticas/getRequerimientos/mes", array('as' => 'estadistica.getRequerimientos', 'uses' => 'EstadisticasController@getReqMes'));
    Route::get("estadisticas/getRequerimientosPorTipo", array('as' => 'estadistica.getRequerimientosTipo', 'uses' => 'EstadisticasController@getReqTipo'));
    Route::get("estadisticas/getTiposReq", array('as' => 'estadistica.getTiposOficios', 'uses' => 'EstadisticasController@getTiposOficios'));
    Route::get("estadisticas/getOrganismos", array('as' => 'estadistica.getOrganismos', 'uses' => 'EstadisticasController@getOrganismos'));
    Route::get("estadisticas/getReqPorOrganismos", array('as' => 'estadistica.getReqPorOrganismos', 'uses' => 'EstadisticasController@getReqPorOrganismos'));


});


Route::post("pedidos_captura/agregarDocumento", array("as" => 'pedidos_captura.agregarDocumento', 'uses' => 'PedidosCapturaController@agregarDocumento'));



Route::when('archivos/*','auth');

Route::group(array('before'=>'cambio_clave'),function() {
    Route::group(array('before' => 'auth'), function () {

            Route::post("usuarios/aceptar",array("as" => "usuarios.aceptar", "uses" => "UsuariosController@aceptar"));
        Route::get('protection', 'ProtectionController@generateProtection');
        Route::get('refresh-protection', 'ProtectionController@generateProtection'); 
        
        Route::resource('oficios','OficiosController');
        Route::get('oficios/busqueda',array('as'=>'oficios.buscar','uses'=>'OficiosController@index'));
        Route::get('files/descargar',array('as'=>'archivos.descargar','uses'=>function(){
            $path = Input::get('q');
            return Response::download($path);
        }));


        //Permisos para el usuario superadmin (5), solo el puede editar y para el accesso a la administracion del sistema
            Route::group(array('before' => 'role:1-5,inicio','after'=>'oficiosModificacion'), function () {
            Route::get("admin/oficios_anio",["as"=>"oficios_anio.index","uses"=>"OficiosController@adminOficiosByAnio"]);
            Route::resource("admin", "AdminController");
            Route::get('consultas_positivas',["as"=>"consultas_positivas.index","uses"=>"ConsultaPositivaController@index"]);
            Route::get('consultas_positivas/{idConsulta}',["as"=>"consulta_positiva.show","uses"=>"ConsultaPositivaController@show"]);

            Route::get("oficios_anio",["as"=>"oficios_anio.get","uses"=>"OficiosController@getOficiosByAnio"]);


            Route::post("miembros/validarDatos",array('as' => 'miembros.validarDatos','uses'  => 'MiembrosController@validarDatos'));
            Route::post("miembros/{id}/actualizar",array('as' => 'miembros.actualizar','uses'  => 'MiembrosController@actualizar'));
            Route::post("miembros/eliminarOperador",array('as' => 'miembros.eliminarOperador','uses'  => 'MiembrosController@eliminarOperador'));
            Route::post("miembros/agregarOperador",array('as' => 'miembros.agregarOperador','uses'  => 'MiembrosController@agregarOperador'));
            Route::post("miembros/listadoOperadores",array('as' => 'miembros.listadoOperadores','uses'  => 'MiembrosController@listadoOperadores'));
            Route::post("miembros/listadoResponsables",array('as' => 'miembros.listadoResponsables','uses'  => 'MiembrosController@listadoResponsables'));
            Route::post("miembros/eliminarResponsable",array('as' => 'miembros.eliminarResponsable','uses'  => 'MiembrosController@eliminarResponsable'));
            Route::post("miembros/agregarResponsable",array('as' => 'miembros.agregarResponsable','uses'  => 'MiembrosController@agregarResponsable'));

            Route::get("suborganismos/organismo/{idOrganismo}",array('as' => 'suborganismo.byorganismo','uses'  => 'SubOrganismoController@getSubOrganismoByIdOrg'));

            Route::resource("miembros", "MiembrosController",array('except' => array('show','index')));


            Route::resource("usuarios", "UsuariosController");
            Route::resource("panel","AdminController");
            Route::resource("mails","CorreosController");
            Route::resource("subOrganismos","SubOrganismoController");
            Route::post('usuarios/restablecer/clave',array("as"=>"usuarios.restablecer","uses"=>"UsuariosController@RestablecerClave"));
//            Route::resource("solicitud_paradero", "OficioSolicitudParaderoController",array('except' => array('show','create','update','edit')));
            Route::resource("solicitud_paradero", "PersonaExtraviadaController",array('except' => array('show','create','update','edit')));
            Route::post("solicitud_paradero/agregarCelular",array('as' => 'solicitud_paradero.agregarCelular','uses'  => 'PersonaExtraviadaController@agregarCelular'));
            Route::post("solicitud_paradero/eliminarCelular",array('as' => 'solicitud_paradero.eliminarCelular','uses'  => 'PersonaExtraviadaController@eliminarCelular'));
//            Route::post("solicitud_paradero/agregarCelular",array('as' => 'solicitud_paradero.agregarCelular','uses'  => 'OficioSolicitudParaderoController@agregarCelular'));
//            Route::post("solicitud_paradero/eliminarCelular",array('as' => 'solicitud_paradero.eliminarCelular','uses'  => 'OficioSolicitudParaderoController@eliminarCelular'));
            Route::get("solicitud_paradero/{rute}/{name}/mostrar_archivo",['as' => 'solicitud_paradero.mostrar_archivo','uses' => 'PersonaExtraviadaController@show']);
            Route::get('solicitud_paradero/show/{id}',["as"=>'solicitud_paradero.show',"uses"=>"PersonaExtraviadaController@showReporte"]);
            Route::resource("secuestro_elementos", "SecuestroElementosController",array('except' => array('show','create','update','edit')));
            Route::resource("secuestro_armas", "SecuestroArmasController",array('except' => array('show','create','update','edit')));
            Route::resource("secuestro_vehicular", "PedidosSecuestroVehicularController",array('except' => array('show','create','update','edit')));
            Route::resource("prohibicion_salida", "ProhibicionSalidaPaisController",array('except' => array('show','create','update','edit')));
            Route::resource("pedidos_captura", "PedidosCapturaController",array('except' => array('show','create','update','edit')));
            Route::resource("medidas_restrictivas", "MedidasRestrictivasController",array('except' => array('show','create','update','edit')));
            Route::resource("solicitud_paradero2", "SolicitudParaderoReqJudController",array('except' => array('show','create','update','edit')));
            Route::resource("habeas_corpus", "HabeasCorpusController",array('except' => array('show','create','update','edit')));
            Route::resource("otras_medidas", "OtrasMedidasController",array('except' => array('show','create','update','edit')));
            Route::get("oficios/vencimiento/{id}",["as"=>"oficios.confirmar.vencimiento","uses"=>"OficiosController@confirmarVencimiento"]);
            Route::get('oficios/autoridad/{idOficio}',["as"=>"oficios.autoridad","uses"=>"OficiosController@getAutoridad"]);
            Route::post('oficios/autoridad/{idOficio}',["as"=>"oficios.autoridad","uses"=>"OficiosController@setAutoridad"]);
            Route::get('grupos_correos',["as"=>"grupo_correos.index","uses"=>"GruposCorreosController@index"]);
            Route::get('grupos_correos/getGrupos',["as"=>"grupo_correos.getGrupos","uses"=>"GruposCorreosController@getGrupos"]);
            Route::post('grupos_correos/grupos/create',["as"=>"grupo_correos.create","uses"=>"GruposCorreosController@createGrupo"]);
            Route::post('grupos_correos/grupos/miembros/add',["as"=>"grupo_correos.miembros.add","uses"=>"GruposCorreosController@createMiembroOrganismo"]);
            Route::post('grupos_correos/grupos/miembros/remove',["as"=>"grupo_correos.miembros.remove","uses"=>"GruposCorreosController@removeMiembroOrganismo"]);
            Route::get('grupos_correos/get/organismos',["as"=>"grupo_correos.getOrganismos","uses"=>"GruposCorreosController@getOrganismos"]);
            Route::get('/grupos_correos/gruposMiembros/{idGrupo}',["as"=>"grupo_correos.gruposMiembros","uses"=>"GruposCorreosController@getMiembrosByGrupo"]);

            Route::get('consultas_positivas',["as"=>"consultas_positivas.index","uses"=>"ConsultaPositivaController@index"]);

app/views/admin/categorias.blade.php
@extends ('header')
@section('scripts')
<style>
    .row {
        margin-top: 5px !important;
    }
</style>
@stop
@section ('content')
<h2>Panel De Administración</h2>
<h3>Usuarios</h3>
<hr>
<div class="row">
    <a href="{{ route('usuarios.create') }}" ><button class="btn btn-primary" >Cargar Usuario <i class="glyphicon glyphicon-user"></i></button></a>
    <a href="{{ route('usuarios.index') }}"><button class="btn btn-primary" >Listado De Usuarios  <i class="glyphicon glyphicon-list-alt"></i></button></a>
    <a href="{{ route('usuarios.clave') }}"><button class="btn btn-primary" >Cambiar Clave  <i class="glyphicon glyphicon-lock"></i></button></a>
</div>







@stop

app/views/admin/form.blade.php
@extends ('header')
@section('scripts')
<style>
    .row {
        margin-top: 5px !important;
    }
</style>
@stop
@section ('content')
@include('errores')

{{ Form::model(isset($descripcion)? $descripcion:null ,$form_data, array('role' => 'form')) }}

<div class="row">
    <div class="form-group col-md-4">
        {{ Form::label('descripcion', 'Descripción') }}
        {{ Form::text('descripcion', null, array('placeholder' => 'Ingrese Descripcion', 'class' => 'form-control')) }}
    </div>

</div>
<div class="row">
    <div class="form-group col-md-4">
        {{ Form::button($action." »", array('type' => 'submit', 'class' => 'btn btn-primary')) }}
    </div>
</div>
{{ Form::close() }}


@stop

app/views/admin/listado.blade.php
0@extends ('header')
@section('scripts')
<style>
    .row {
        margin-top: 5px !important;
    }
</style>
@stop
@section ('content')

<table class="table responsive table-bordered table-hover">
    <thead>
        <th>Descripción</th>
        <th>Acciones</th>
    </thead>
    <tbody>
    @foreach ($descripciones as $descripcion)
        <tr>
            <td>{{ $descripcion->descripcion }}</td>
            <td><a href="{{ route($ruta,$descripcion->id) }}"><button class="btn btn-info">Editar</button></a></td>
        </tr>
    @endforeach
    </tbody>
</table>
<a href="{{ $UrlCrear }}"><button class="btn btn-success">Crear »</button></a>
@stop

app/views/admin/listados_grupos_correos.blade.php
@extends('header')
@section('content')

<div id="grupoCorreos">
	<div class="row">
		<div class="col-md-12">
			<button class="btn btn-default" v-on="click:crearGrupo">Crear Grupo</button>
				
		</div>
	</div>

	<table class="table table-responsive" style="margin-top:10px;">
		<thead>
			<th>Descripcion</th>
			<th>Acciones</th>
		</thead>
		<tbody>
			<tr v-repeat="grupos">
				<td>
					<a href="#" id="descripcion_grupo" data-type="text" data-pk="1" data-url="/post" data-title="Enter username">@{{descripcion}}</a>
					
				</td>
				<td>
					<button class="btn btn-default" v-on="click:agregarOrganismo(id,descripcion)">Organismos</button>
					<!--<button class="btn btn-danger">Eliminar</button>-->
				</td>
			</tr>

		</tbody>
	</table>

	@include('admin.modals.grupos_correos_create')
	@include('admin.modals.grupos_correos_add_organismo')












</div>




@stop


@section('scripts')
{{ HTML::script('assets/js/vue.min.js') }}
{{ HTML::script('assets/js/bootstrap-switch.min.js') }}
{{ HTML::script('assets/js/gruposCorreos.js') }}

@stop

app/views/admin/oficios_vencidos.blade.php
@extends('header')
@section('content')

	<table class="table responsive table-bordered table-hover table-striped" id="tablaOficios" style="margin-top: 1em !important">
    <thead>
    <tr>
        <td>N° Requerimiento</td>
        <td>Tipo de Medida</td>
        <td>Fecha de Carga del Req</td>
        <td>Estado</td>
        <td>Alerta Temprana</td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody id="bodyOficios">
    @foreach ($oficios as $oficio)
    <tr class="{{ ($oficio->estado==2) ? 'danger' : 'info' }} {{ ($oficio->plazo_autorizado == 1) ? 'warning':'' }}">
        <td>{{ $oficio->id }}</td>
        <td>{{ $oficio->tipo->descripcion }} @if(($oficio->tipo->id == 9) or ($oficio->tipo->id == 5 )) ({{$oficio->medida_restrictiva}}) @endif</td>
        <td>{{ $oficio->created_at }}  </td>
        <td>
            @if($oficio->tipo_oficio==3)
                @if($oficio->estadoOficio->id == 1 && $oficio->plazo_autorizado == 1)
                    Autorizado
                @else
                    {{ $oficio->estadoOficio->descripcion }}
                @endif
            @else
                {{ $oficio->estadoOficio->descripcion }} <br>
                @if($oficio->estado == 2) {{$oficio->oficioCesado->created_at}} @endif
            @endif
        </td>
        <td>@if($oficio->alerta_temprana ==1)
            <span class="label label-danger">SI</span> @else <span class="label label-success">NO</span>@endif
        </td>
        <td>
            <a href='{{ route($oficio->tipo->ruta.".show",$oficio->id) }}' class=" tooltip-test"  data-toggle="tooltip" data-placement="top" title="Ver Reporte"><i class="fa fa-eye"></i></a>
           
            <a href='{{ route($oficio->tipo->ruta.".pdf",$oficio->id) }}' target="_blank" class=" tooltip-test"  data-toggle="tooltip" data-placement="top" title="Descargar Reporte"><i class="fa fa-download"></i></a>

            <a href="" data-toggle="tooltip" data-placement="top" title="Marcar como revisado"><i class="fa fa-check"></i></a>
            
        </td>
     
    </tr>

    @endforeach
    


    </tbody>

</table>

@stop

app/views/admin/panel.blade.php
@extends ('header')
@section('scripts')
<style>
    .row {
        margin-top: 5px !important;
    }
</style>
@stop
@section ('content')
<h2>Panel de Administración</h2>
<div class="panel panel-info">
    <div class="panel-heading">Administración de Usuarios</div>
    <div class="panel-body">
    <div class="row">
        <div class="form-group col-md-12">
            <a href={{ route('usuarios.create') }} ><button class="btn btn-primary" >Cargar Usuario <i class="fa fa-user"></i></button></a>
            <a href={{ route('usuarios.index')  }} ><button class="btn btn-primary" >Listado De Usuarios  <i class="fa fa-users"></i></button></a>
            <a href={{ route('usuarios.clave')  }} ><button class="btn btn-primary" >Cambiar Clave  <i class="fa fa-lock"></i></button></a>
            <!--<a href={{ route('estadistica.requerimientos')  }} ><button class="btn btn-primary" >Estadistica  <i class=""></i></button></a>-->
        </div>
    </div>
   </div>
 </div>

<div class="panel panel-info">
    <div class="panel-heading">Lista de Correos</div>
    <div class="panel-body">
        <div class="row">
            <div class="form-group col-md-12">
                <a href="{{ route('mails.create') }}"><button class="btn btn-info " >Cargar Mail <i class="fa fa-envelope"></i></button></a>
                <a href="{{ route('mails.index') }}"><button class="btn btn-info " >Listado De Mails  <i class="fa fa-list"></i></button></a>
                <a href="{{ route('grupo_correos.index') }}"><button class="btn btn-info " >Grupos de Correos  <i class="fa fa-list"></i></button></a>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">Organismos</div>
    <div class="panel-body">
        <div class="row">
            <div class="form-group col-md-12">
                <a href="{{ route('subOrganismos.create') }}"><button class="btn btn-info " >Cargar Sub-Organismo <i class="glyphicon glyphicon-book"></i></button></a>
                <a href="{{ route('subOrganismos.index') }}"><button class="btn btn-info " >Listado de Sub-Organismos <i class="fa fa-list"></i></button></a>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">Miembros</div>
    <div class="panel-body">
        <div class="row">
            <div class="form-group col-md-12">
                <a href={{ route('miembros.create') }} ><button class="btn btn-primary" >Cargar Miembro <i class="fa fa-user"></i></button></a>
                <a href="{{ route('miembros.index') }}"><button class="btn btn-primary " >Listado de Miembros  <i class="fa fa-users"></i></button></a>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">Estadísticas</div>
    <div class="panel-body">
        <div class="row">
            <div class="form-group col-md-12">
                <a href="{{ route('solicitud_paradero.estadisticas') }}"><button class="btn btn-primary " >Búsqueda de personas  <i class="fa fa fa-list"></i></button></a>
                <a href="{{ route('solicitud_paradero.estadisticas') }}"><button class="btn btn-primary " >Alerta de consulta positiva  <i class="fa fa fa-list"></i></button></a>
            </div>
        </div>
    </div>
</div>

<!--
<div class="panel panel-info">
    <div class="panel-heading">Requerimientos</div>
    <div class="panel-body">
        <div class="row">
            <div class="form-group col-md-4">
                <a href={{ route('consultas_positivas.index') }} ><button class="btn btn-primary" >Consultas Positivas<i class="fa fa-user"></i></button></a>
                
            </div>
            <div class="form-group col-md-4">
                <a href={{ route('oficios_anio.index') }} ><button class="btn btn-primary" >Requerimientos que cumplieron un año <i class="fa fa-user"></i></button></a>
                
            </div>
        </div>
    </div>
</div>-->
@stop